kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    type: frontend
    deployment: blue
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80